apiVersion: v2
name: mefobase-system
description: Helm chart cho du an CSDL Mefobase (Production Deployment)
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
    - name: Nguyen Anh Huy
      email: huyna@etc.vn
